# Generated by Django 3.2.9 on 2021-12-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False, verbose_name='Category ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
            ],
        ),
    ]
