# Generated by Django 3.2.9 on 2021-12-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_category_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id_institution', models.AutoField(primary_key=True, serialize=False, verbose_name='Institution ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
            ],
            options={
                'db_table': 'institution',
            },
        ),
    ]
