# Generated by Django 3.2.9 on 2021-12-20 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20211219_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Institution', 'verbose_name_plural': 'Institutions'},
        ),
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
    ]
