# Generated by Django 3.2.9 on 2021-12-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_alter_course_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='workload',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Workload'),
        ),
    ]
