# Generated by Django 3.2.9 on 2021-12-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_auto_20211220_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='formation',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses', to='mysite.Formation'),
        ),
    ]
