# Generated by Django 3.2.6 on 2022-02-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_auto_20211231_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='curriculum_map',
            field=models.TextField(blank=True, null=True, verbose_name='Curriculum Map'),
        ),
    ]
