# Generated by Django 3.2.9 on 2025-06-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0018_auto_20220224_1323"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="name",
            field=models.CharField(max_length=120, verbose_name="Name"),
        ),
    ]
