# Generated by Django 3.2.9 on 2025-11-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0019_alter_institution_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
    ]
